#!/usr/bin/bash

# Simplistic CLI script for testing websocket integration.
#  Adding a socket file would work, too. Requires
#  websocat.

HOST=localhost:8000

while read p; do
  echo -n "Orin: "
  echo "$p" | websocat ws://$HOST/chat | while IFS= read -r delta; do
    if [ "$delta" = "" ]; then
      echo
    fi
    printf "%s" "$delta"
  done
  echo
  echo -n "User: "
done
